/**
 * Seed reviewers into the database.
 * Run: npm run seed:reviewers
 */
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("../config/db");
const Reviewer = require("../models/Reviewer");

const IMPORTANT_NOTES = [
  { title: "⏱️ Time Management is Key", text: "The exam is 3 hours and 10 minutes long. Use your time wisely—pace yourself and avoid spending too long on any single question." },
  { title: "❌ No \"Negative Marking\"", text: "Don't be afraid to guess. You won't lose points for wrong answers, so try to answer every question." },
  { title: "💡 You can skip questions", text: "Navigate freely and come back to difficult items later. Use the question list to track your progress." },
  { title: "✅ Review your answers", text: "After completion you'll get your score and a detailed breakdown by subject. Use this to focus your review." },
  { title: "🎯 Simulate the actual environment", text: "Find a quiet space and minimize distractions. Practicing under exam-like conditions helps build confidence." },
  { title: "🔍 Answer Review Available", text: "After the exam, correct answers and explanations are available so you can learn from every question." },
  { title: "🧠 Heads up!", text: "Questions are uniquely generated by BrainyBesh.ai to give you a fresh practice experience each time." },
];

const REVIEWERS = [
  {
    slug: "cse-professional",
    type: "mock",
    access: "free",
    title: "Civil Service Mock Exam (Professional Level)",
    description: {
      short: "For aspiring government professionals.",
      full: "Take this exam if you're aiming for technical, admin, or supervisory positions in government. Questions on logic, math, grammar, general knowledge, and more.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "170 items", duration: "3h 10m", passingRate: "80%", accessLevel: null },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["professional", "both"],
      totalItems: 170,
      timeLimitSeconds: 11400, // 3h 10m
      passingThreshold: 80,
      sectionDistribution: [
        { section: "verbal", count: 45 },
        { section: "numerical", count: 40 },
        { section: "analytical", count: 55 },
        { section: "general information", count: 30 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "03:10:00",
      itemsCount: 170,
      progress: "Not Started",
      bannerImage: null,
      coverage: [
        { subject: "General Information", itemCount: "20 items", topics: ["Philippine Constitution", "Code of Conduct and Ethical Standards for Public Officials and Employees (R.A. 6713)", "Peace and Human Rights Issues and Concepts", "Environment Management and Protection."] },
        { subject: "Numerical Ability", itemCount: "30-35 items", topics: ["Basic Operations", "Word Problems", "Number Series", "Time, Distance, and Work Problems", "Fractions, Decimals, Percentages."] },
        { subject: "Analytical Ability / Logic", itemCount: "30-35 items", topics: ["Logical reasoning", "Pattern analysis", "Syllogisms."] },
        { subject: "Verbal Ability", itemCount: "35-40 items", topics: ["Grammar and Correct Usage", "Vocabulary", "Paragraph Organization", "Reading Comprehension."] },
      ],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-subprofessional",
    type: "mock",
    access: "premium",
    title: "Civil Service Mock Exam (Sub-Professional)",
    description: {
      short: "For entry-level clerical roles.",
      full: "Designed for those seeking clerical or administrative support positions in government. Focuses on basic math, grammar, clerical ability, and general information",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "165 items", duration: "2h 40m", passingRate: "80%", accessLevel: null },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["subprofessional", "both"],
      totalItems: 165,
      timeLimitSeconds: 9600, // 2h 40m
      passingThreshold: 80,
      sectionDistribution: [
        { section: "verbal", count: 45 },
        { section: "numerical", count: 40 },
        { section: "clerical", count: 50 },
        { section: "general information", count: 30 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "02:40:00",
      itemsCount: 165,
      progress: "Not Started",
      bannerImage: null,
      coverage: [
        { subject: "Clerical Ability", itemCount: "varies", topics: ["Alphabetizing", "Record keeping", "Following instructions."] },
        { subject: "General Information", itemCount: "varies", topics: ["Philippine Constitution", "Code of Conduct (R.A. 6713)", "Basic civic concepts."] },
      ],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-practice-verbal",
    type: "practice",
    access: "premium",
    title: "Civil Service Practice Exam (Verbal Ability)",
    description: {
      short: "Sharpen your grammar and comprehension skills.",
      full: "Covers English grammar, vocabulary, sentence structure, and reading comprehension—key areas to help you understand and answer questions accurately.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "50 items", duration: "Approx. 45m", passingRate: null, accessLevel: "Prof & Sub-Prof" },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["professional", "subprofessional", "both"],
      totalItems: 50,
      timeLimitSeconds: 2700, // 45m
      passingThreshold: null,
      sectionDistribution: [
        { section: "verbal", count: 50 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "00:45:00",
      itemsCount: 50,
      progress: "Not Started",
      bannerImage: null,
      coverage: [{ subject: "Verbal Ability", itemCount: "50 items", topics: ["Grammar and Correct Usage", "Vocabulary", "Paragraph Organization", "Reading Comprehension."] }],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-practice-analytical",
    type: "practice",
    access: "premium",
    title: "Civil Service Practice Exam (Analytical Ability)",
    description: {
      short: "Train your mind to solve patterns and puzzles.",
      full: "Improve your skills in logical reasoning, pattern recognition, syllogisms, and problem solving—essential for tackling tough situational questions.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "50 items", duration: "Approx. 45m", passingRate: null, accessLevel: "Prof only" },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["professional", "both"],
      totalItems: 50,
      timeLimitSeconds: 2700,
      passingThreshold: null,
      sectionDistribution: [
        { section: "analytical", count: 50 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "00:45:00",
      itemsCount: 50,
      progress: "Not Started",
      bannerImage: null,
      coverage: [{ subject: "Analytical Ability / Logic", itemCount: "50 items", topics: ["Logical reasoning", "Pattern analysis", "Syllogisms."] }],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-practice-clerical",
    type: "practice",
    access: "premium",
    title: "Civil Service Practice Exam (Clerical Ability)",
    description: {
      short: "Perfect for clerical and administrative tasks.",
      full: "Test your attention to detail, alphabetizing, record keeping, and ability to follow instructions—critical for clerical work in government.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "50 items", duration: "Approx. 40m", passingRate: null, accessLevel: "Sub-Prof only" },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["subprofessional", "both"],
      totalItems: 50,
      timeLimitSeconds: 2400, // 40m
      passingThreshold: null,
      sectionDistribution: [
        { section: "clerical", count: 50 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "00:40:00",
      itemsCount: 50,
      progress: "Not Started",
      bannerImage: null,
      coverage: [{ subject: "Clerical Ability", itemCount: "50 items", topics: ["Attention to detail", "Alphabetizing", "Record keeping", "Following instructions."] }],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-practice-numerical",
    type: "practice",
    access: "premium",
    title: "Civil Service Practice Exam (Numerical Ability)",
    description: {
      short: "Master numbers and word problems.",
      full: "Practice basic math operations, fractions, percentages, ratios, time-speed-distance problems, and more to strengthen your quantitative reasoning.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "50 items", duration: "Approx. 45m", passingRate: null, accessLevel: "Prof & Sub-Prof" },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["professional", "subprofessional", "both"],
      totalItems: 50,
      timeLimitSeconds: 2700,
      passingThreshold: null,
      sectionDistribution: [
        { section: "numerical", count: 50 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "00:45:00",
      itemsCount: 50,
      progress: "Not Started",
      bannerImage: null,
      coverage: [{ subject: "Numerical Ability", itemCount: "50 items", topics: ["Basic Operations", "Word Problems", "Number Series", "Fractions, Decimals, Percentages."] }],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-practice-general",
    type: "practice",
    access: "premium",
    title: "Civil Service Practice Exam (General Info)",
    description: {
      short: "Review Philippine laws and civic concepts.",
      full: "Focuses on the 1987 Constitution, RA 6713 (Code of Conduct), human rights, and environmental awareness—vital knowledge for all civil servants.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "50 items", duration: "Approx. 40m", passingRate: null, accessLevel: "Prof & Sub-Prof" },
    status: "published",
    examConfig: {
      variant: "dynamic",
      examFamily: "cse",
      examLevel: ["professional", "subprofessional", "both"],
      totalItems: 50,
      timeLimitSeconds: 2400,
      passingThreshold: null,
      sectionDistribution: [
        { section: "general information", count: 50 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "00:40:00",
      itemsCount: 50,
      progress: "Not Started",
      bannerImage: null,
      coverage: [{ subject: "General Info", itemCount: "50 items", topics: ["1987 Constitution", "R.A. 6713 (Code of Conduct)", "Human rights", "Environmental awareness."] }],
      importantNotes: IMPORTANT_NOTES,
    },
  },
  {
    slug: "cse-demo",
    type: "demo",
    access: "free",
    title: "Civil Service Exam - (Demo Review)",
    description: {
      short: "Try a short sample exam.",
      full: "A short demo to get familiar with the exam format and question types. No time limit.",
    },
    logo: { filename: "cselogo.png", path: "/assets/cselogo.png" },
    details: { items: "20 items", duration: "No time limit", passingRate: null, accessLevel: null },
    status: "published",
    examConfig: {
      variant: "fixed",
      examFamily: "cse",
      examLevel: ["professional", "both"],
      fixedQuestionSetId: "demo_cse_professional_v1",
      totalItems: 20,
      timeLimitSeconds: 0, // no time limit
      passingThreshold: null,
      sectionDistribution: [
        { section: "verbal", count: 5 },
        { section: "numerical", count: 5 },
        { section: "analytical", count: 6 },
        { section: "general information", count: 4 },
      ],
      difficultyDistribution: { easy: 30, medium: 50, hard: 20 },
    },
    examDetails: {
      timeFormatted: "No time limit",
      itemsCount: 20,
      progress: "Not Started",
      bannerImage: null,
      coverage: [{ subject: "Sample topics", itemCount: "20 items", topics: ["Mixed sample questions to familiarize you with the exam format."] }],
      importantNotes: IMPORTANT_NOTES,
    },
  },
];

async function seed() {
  await connectDB();

  console.log("🗑  Clearing existing reviewers...");
  await Reviewer.deleteMany({});

  console.log("📝  Inserting reviewers...");
  const docs = await Reviewer.insertMany(REVIEWERS);
  console.log(`✅  ${docs.length} reviewers seeded successfully!`);

  // Print ID mapping so frontend can reference them
  console.log("\n📋  Reviewer ID mapping:");
  docs.forEach((d) => console.log(`   ${d.slug}  →  ${d._id}`));

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌  Seeding failed:", err);
  process.exit(1);
});
