/**
 * One-time script to update the cse-professional reviewer's section distribution,
 * coverage, disclaimer, difficultyText, and important notes to the correct values:
 *   Verbal: 51 items (30%)
 *   Analytical: 60 items (35%)
 *   Numerical: 51 items (30%)
 *   General Information: 8 items (5%)
 *
 * Run: node backend/scripts/updateCseProfessionalDistribution.js
 */
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("../config/db");
const Reviewer = require("../models/Reviewer");

async function run() {
  await connectDB();

  const result = await Reviewer.findOneAndUpdate(
    { slug: "cse-professional" },
    {
      $set: {
        "details.duration": "3h 10m",
        "examConfig.timeLimitSeconds": 11400,
        "examDetails.timeFormatted": "03:10:00",
        "examConfig.sectionDistribution": [
          { section: "verbal", count: 51 },
          { section: "analytical", count: 60 },
          { section: "numerical", count: 51 },
          { section: "general information", count: 8 },
        ],
        "examDetails.coverage": [
          {
            subject: "Verbal Ability",
            itemCount: "51 items",
            topics: [
              "Word Meaning",
              "Sentence Completion",
              "Error Recognition",
              "Sentence Structure",
              "Paragraph Organization",
              "Reading Comprehension",
            ],
          },
          {
            subject: "Analytical Ability",
            itemCount: "60 items",
            topics: [
              "Word Analogy",
              "Symbolic Logic / Abstract Reasoning",
              "Identifying Assumption and Drawing Conclusion",
              "Data Interpretation",
            ],
          },
          {
            subject: "Numerical Ability",
            itemCount: "51 items",
            topics: [
              "Basic Operations",
              "Number Sequence",
              "Word Problems",
            ],
          },
          {
            subject: "General Information",
            itemCount: "8 items",
            topics: [
              "Philippine Constitution",
              "Code of Conduct and Ethical Standards for Public Officials and Employees (R.A. 6713)",
              "Peace and Human Rights Issues and Concepts",
              "Environment Management and Protection",
            ],
          },
        ],
        "examDetails.breakdownFootnote": "Coverage aligned to CSC scope. Item distribution may vary in the actual exam.",
        "examDetails.disclaimer": "This mock exam is designed to closely simulate the format and difficulty of the Civil Service Exam but does not guarantee identical questions, coverage, or results in the actual examination.",
        "examDetails.difficultyText": "Difficulty varies per section, similar to the actual Civil Service Exam.",
        "examDetails.importantNotes": [
          {
            title: "⏱️ Time Management is Key",
            text: "This mock exam is strictly timed at 3 hours and 10 minutes. Pacing yourself is crucial!",
          },
          {
            title: "❌ No \"Negative Marking\"",
            text: "Don't be afraid to guess! There's no deduction for wrong answers, so try to answer all questions.",
          },
          {
            title: "💡 You can skip questions",
            text: "Feel free to skip difficult questions and come back to them later if you have time.",
          },
          {
            title: "✅ Review your answers",
            text: "Once you finish, our system will immediately show your score and a detailed breakdown of your performance per subject area. You can also review your answers with explanations.",
          },
          {
            title: "🧠 Heads up!",
            text: "All questions in this mock exam are uniquely generated by Reviewly's advanced AI to give you fresh challenges every time.",
          },
        ],
      },
    },
    { new: true }
  );

  if (!result) {
    console.error("ERROR: cse-professional reviewer not found.");
    process.exit(1);
  }

  console.log("Updated sectionDistribution:");
  console.log(JSON.stringify(result.examConfig.sectionDistribution, null, 2));
  console.log("\nUpdated coverage:");
  result.examDetails.coverage.forEach((c) =>
    console.log(`  ${c.subject}: ${c.itemCount}`)
  );
  console.log("\nDuration:", result.details?.duration);
  console.log("Time limit seconds:", result.examConfig?.timeLimitSeconds);
  console.log("Formatted time:", result.examDetails?.timeFormatted);
  console.log("\nBreakdown footnote:", result.examDetails.breakdownFootnote);
  console.log("Disclaimer:", result.examDetails.disclaimer);
  console.log("Important notes count:", result.examDetails.importantNotes.length);

  await mongoose.disconnect();
  console.log("\nDone.");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
